name: Makefile CD

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Python 3.8  # for generating versioninfo.json
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Compile for all supported targets
      run: make compile-all

    - name: GH Release Artefacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/wintersocks5.armon-darwin-amd64
          ./dist/wintersocks5.armon-darwin-arm64
          ./dist/wintersocks5.armon-linux-386
          ./dist/wintersocks5.armon-linux-amd64
          ./dist/wintersocks5.armon-linux-arm
          ./dist/wintersocks5.armon-linux-arm64
          ./dist/wintersocks5.armon-windows-386.exe
          ./dist/wintersocks5.armon-windows-amd64.exe
          ./dist/wintersocks5.txthinking-darwin-amd64
          ./dist/wintersocks5.txthinking-darwin-arm64
          ./dist/wintersocks5.txthinking-linux-386
          ./dist/wintersocks5.txthinking-linux-amd64
          ./dist/wintersocks5.txthinking-linux-arm
          ./dist/wintersocks5.txthinking-linux-arm64
          ./dist/wintersocks5.txthinking-windows-386.exe
          ./dist/wintersocks5.txthinking-windows-amd64.exe
